### ISSUE TITLE
Bug Image can't be saved in app and web is dead

### ISSUE THREAD

**Issue by 01soni247** [wiryaimd/manga-translator#1]

**Comment by wiryaimd** [comment]
Thanks for your report, the web is under improvement i will fix the app and turn on it later

**Comment by 01soni247** [comment]
> Thanks for your report, the web is under improvement i will fix the app and turn on it later

Enggak ke rasa dah beberapa bulan

**Comment by wiryaimd** [comment]
> > Thanks for your report, the web is under improvement i will fix the app and turn on it later
> 
> Enggak ke rasa dah beberapa bulan

sabar ngap lagi sibuk lomba

**Comment by 01soni247** [comment]
> > > Thanks for your report, the web is under improvement i will fix the app and turn on it later
> > 
> > 
> > Enggak ke rasa dah beberapa bulan
> 
> sabar ngap lagi sibuk lomba

Iya maaf ngap
